insert into role(name) values ('user');
insert into role(name) values ('root');
insert into role(name) values ('superuser');
insert into users(name, role_id) values ('Ivan', 1);
insert into users(name, role_id) values ('Vasil', 1);
insert into users(name, role_id) values ('Petr', 2);
insert into users(name, role_id) values ('Sidr', 3);
insert into rules(name) values ('rule1');
insert into rules(name) values ('rule2');
insert into rules(name) values ('rule3');
insert into category(name) values ('category1');
insert into category(name) values ('category2');
insert into category(name) values ('category3');
insert into state(name) values ('state1');
insert into state(name) values ('state2');
insert into state(name) values ('state3');
insert into item(name, users_id, category_id, state_id) values ('item1', 1, 2, 1);
insert into item(name, users_id, category_id, state_id) values ('item2', 2, 2, 3);
insert into item(name, users_id, category_id, state_id) values ('item3', 3, 3, 2);
insert into item(name, users_id, category_id, state_id) values ('item4', 1, 1, 3);
insert into attachs(name, item_id) values ('attachs1', 3);
insert into attachs(name, item_id) values ('attachs2', 2);
insert into attachs(name, item_id) values ('attachs3', 4);
insert into attachs(name, item_id) values ('attachs4', 1);
insert into comments(name, item_id) values ('comments1', 3);
insert into comments(name, item_id) values ('comments2', 2);
insert into comments(name, item_id) values ('comments3', 4);
insert into comments(name, item_id) values ('comments4', 1);